application: biopixology
version: 1
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /app.comp.js
  static_files: app.comp.js
  upload: app.comp.js

- url: /app.comp.js.map
  static_files: app.comp.js.map
  upload: app.comp.js.map


# - - - - -
# Dev only
# v-v-v-v-v
- url: /app.js
  static_files: app.js
  upload: app.js

- url: /deps.js
  static_files: deps.js
  upload: deps.js

- url: /lib
  static_dir: lib

- url: /src
  static_dir: src
# ^ ^ ^ ^ ^
# Dev only
# - - - - -


- url: /about
  script: about.php

- url: /play
  script: play.php

- url: /.*
  script: index.php
