application: biopixology
version: 1
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /about.php
  static_files: about.php
  upload: about.php

- url: /app.comp.js
  static_files: app.comp.js
  upload: app.comp.js

- url: /app.comp.js.map
  static_files: app.comp.js.map
  upload: app.comp.js.map

- url: /.*
  script: index.php
