// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['app.go'], ['app.Board', 'app.Canvas', 'app.GameLoop', 'goog.dom']);
goog.addDependency('../../../src/app/Board.js', ['app.Board'], ['app.Cell']);
goog.addDependency('../../../src/app/Canvas.js', ['app.Canvas'], ['goog.dom']);
goog.addDependency('../../../src/app/Cell.js', ['app.Cell'], []);
goog.addDependency('../../../src/app/GameLoop.js', ['app.GameLoop'], []);
goog.addDependency('../../../src/app/ImageProcessor.js', ['app.ImageProcessor'], []);
