// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['app.go'], []);
goog.addDependency('../../../src/app/Cell.js', ['app.Cell'], []);
