// This file was autogenerated by ./lib/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app.js', ['app.go'], ['app.Canvas', 'goog.dom']);
goog.addDependency('../../../src/app/Canvas.js', ['app.Canvas'], ['goog.dom']);
goog.addDependency('../../../src/app/Cell.js', ['app.Cell'], []);
